### ISSUE TITLE
[Teacher] Manage Dish

### ISSUE THREAD

**Issue by channakchhon** [pnc-virtual-company/2018-canteen#105]
Updating does not work without image uploaded

**Comment by channakchhon** [comment]
Cancel does not work after we click update

**Comment by channakchhon** [comment]
After adding new dish it should be appeared in the top row of the data table

**Comment by matthieuderoo** [comment]
Difference between the 2 fields "Meal time" and "Dish time" in the form "Add New Dish" is not clear

**Comment by channakchhon** [comment]
Error on foreign key constraint when we try to delete a dish.
"Cannot delete or update a parent row: a foreign key constraint fails (`2018vc2ge_canteen`.`tbl_dish_user`, CONSTRAINT `fk_tbl_dish_has_tbl_users_tbl_dish1` FOREIGN KEY (`dish_id`) REFERENCES `tbl_dishes` (`dish_id`) ON DELETE NO ACTION ON UPDATE NO ACTION)

DELETE FROM `tbl_dishes` WHERE `dish_id` = '10'""
